sudo: required
dist: trusty
language: node_js
node_js:
- '5'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - php5-cli
    - zip
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
branches:
  except:
  - /^v[0-9]/
before_install:
- npm set progress=false
- npm prune
before_script: npm test
script: npm run prod
env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=development
  - secure: lYq6VTIecXHlMeCfn0Bv1hzsEHSjeZQaMUvITuivKssnxPioTQOw+NUmtUvr5ro8fnKuEOoof8ucGdA1GcUXq6NcI2toAHU6MDHb3cSJuoXiAdt9PZcqp6bhjYCNPGFjDbxRmOxzLMLMnF6QwXlWSNvqpa+fI29V7rBjnTyfJ9z+qQeOFu5FX4onKdPvg/snmXZmv8BsnsSTP+zQLLVoxgim6zw35ABz3jLJJbsU/U1i6lof7Bmlxa1GseOe0NF2Ih+NDGGfAgH8DsZiS51s/CaMIF4yKgEdpCgVecD5OJpH6u+LilLBUZ2EeS5jc5OhINqdYqLiq+fqkFwslVvTN99M1u2PhV+/gJMxRypmrSNLG4nhYlT3XufqHvxS4lHM4FaXxN1QGWR6PoKVoXaq5OH/1SEOjWfqTXPzcMrJve13RTCRgQSCU01vKobrZoR+t5GTQ1TEvBoK0MaHxm/fg7lilXlU7FBeX/CDY/n01WJRT014vZNsS6LvY3/VNwXv8OIgbrZplQxe7jGCzFdbkA/RwC9mLemvnPIMDHJPVJrLGU2akUMpzmmslbAVtfdwteQ5YEeZlxCkhUjMJN6BFvORWSoMzqeSHmNkKCkDUZAuBSNW3YQR8a5jRCyw6iTAHVUi1u6XE2zus1cKg7HJ1DA0GJFWCye2wLQxmMpmTu8=
before_deploy:
  - zip -r release.zip ../you_should_probably_change_this/*
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG $GIT_TAG
deploy:
  provider: releases
  api_key:
    secure: lYq6VTIecXHlMeCfn0Bv1hzsEHSjeZQaMUvITuivKssnxPioTQOw+NUmtUvr5ro8fnKuEOoof8ucGdA1GcUXq6NcI2toAHU6MDHb3cSJuoXiAdt9PZcqp6bhjYCNPGFjDbxRmOxzLMLMnF6QwXlWSNvqpa+fI29V7rBjnTyfJ9z+qQeOFu5FX4onKdPvg/snmXZmv8BsnsSTP+zQLLVoxgim6zw35ABz3jLJJbsU/U1i6lof7Bmlxa1GseOe0NF2Ih+NDGGfAgH8DsZiS51s/CaMIF4yKgEdpCgVecD5OJpH6u+LilLBUZ2EeS5jc5OhINqdYqLiq+fqkFwslVvTN99M1u2PhV+/gJMxRypmrSNLG4nhYlT3XufqHvxS4lHM4FaXxN1QGWR6PoKVoXaq5OH/1SEOjWfqTXPzcMrJve13RTCRgQSCU01vKobrZoR+t5GTQ1TEvBoK0MaHxm/fg7lilXlU7FBeX/CDY/n01WJRT014vZNsS6LvY3/VNwXv8OIgbrZplQxe7jGCzFdbkA/RwC9mLemvnPIMDHJPVJrLGU2akUMpzmmslbAVtfdwteQ5YEeZlxCkhUjMJN6BFvORWSoMzqeSHmNkKCkDUZAuBSNW3YQR8a5jRCyw6iTAHVUi1u6XE2zus1cKg7HJ1DA0GJFWCye2wLQxmMpmTu8=
  file: release.zip
  on:
    repo: medfreeman/wp-theme-starter
    branch: travisci
    tags: false
