sudo: required
dist: trusty
language: node_js
node_js:
- '5'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - php5-cli
    - zip
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
branches:
  except:
  - "/^build/"
before_install:
- npm set progress=false
- npm prune
before_script: npm test
script: npm run prod
env:
  global:
  - CXX=g++-4.8
  - NODE_ENV=development
  - REPO_NAME=$(basename $TRAVIS_REPO_SLUG)
  - PROJECT_NAME=$(./travis/getName.js)
  - GIT_TAG=$(./travis/getVersion.js)
  - secure: jpeATxY2WVpnOUk1iHMTG1xR82VL0lLCWR6Zhouepik01NyP5n7Y+/fcBCiwySWdyR5zIo1eTOu9sBtfv1iSNpB8cz1vnYSAMpbJfSsm/ApvRE45NQAGJQbocVXBMWstk1fICtfsAfQGMFCdsXdVrfoKRChb8LlSfcN/opj9/Cr6/FN0Db3osZLAcVI/kPhxpD2D3OTdB4z+CoF8LdCisL0zNbN2qObGfIXajJOiEDpfbhxIXVxwQKgDdOTXq2gOxV08NklSeHoUxI55LWwT8nGFAx8JDuJqfWk2Uge2VX9lGWzG8v9ULQWYzhvx+As35WsfRlrxsRg5GWjbkmkU35ZYzvXckgMvKZy6ABOpb48PyDnftTii0G2YgsrO/HnQXU+SZAS/zqlfannC5imzpPnhI7wUptHwsqehWgtztvpBJELOt2oaz7b1AJyhUk/UtWoEpUp3TygJR+TCfhAWAJyKI1NzNOE50aHUgRewPp3cY8HnHpVYcXL/8ajpxQ5F+svqQ6M+31KPLRwd53E+OsOHIInz0ZyLzYChLqn8ZnQrKLMjLWUSD6gMFFMc+Nmg2N1aekszqYptansrkNayq7ToUK8p9h3i0mmgDS29J8wnvB4BiEiRL6ygt85igEpgK76aECrnCNMnHxNc4zEgBHmeUalX2vMWa5k5sPJeIgA=
before_deploy:
- cd ../$PROJECT_NAME/
- zip -r "../${REPO_NAME}-${GIT_TAG}.zip" ./*
- cd $TRAVIS_BUILD_DIR
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER on
  branch $TRAVIS_BRANCH"
- git push --quiet https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG $GIT_TAG > /dev/null
  2>&1
deploy:
  provider: releases
  skip_cleanup: true
  api-key:
    secure: C+lC1WTmoauEn6Qovfl2sB/fhn2AC6ns2DtiXrdBrE3FaPDuQfQGAJhDbjHw+l/AE/zKIlyq4o17XYT6F3ZQBazzaST1wkydN3uHVJST3SrA+0BGnOXnBAX7//gutweel2vXOUvyn0XsC+oQD6O+rvD41W0aWjrJfMAUjPUEKSs/Ub5IxpR0rqBL4z5ovz0TT7VBuK5xk3Vh7xPtMK6fAjfp9YkEBCj4ZMTPVAvNyk7ewVfjZ1F3xloF/yqXdogiPl12ow0LTKViobVhgIOUQndnrF5EOTyMw7s19iX4ewSbljefDu/urQPe7cfaWvXgWdQlZCDRTWf0MAl3rGDX3a2k7MjFacz/4zRibUxKfkZ+BCutB41262VuBjnmIIt4y+/Kdep68z1S5fc48WCPc2jUxo5T2cFfC/VDLyba4jN/H5BeHgr28sZBQO1NuK8myZRWDKBzcWZ+4DkY+VciN87tRc7Xch7rUnN7tUpC8uPLJ2pUEU8AsU1Hn2Fs3+aCYbz42pJ8DBkAUoXsu7z3vXQiUIueU6crzjGYewRRagNMav1x5TmAClZxZjD0HILOM0jQrpKQvFy8YBstSlja11fXKi7/yLWXVVJLJB0eYT+y2sPUYRqkdW9ahyGHltqXaXXJK5/wAuNFJ8em/sQlccUMLsTr6vNX3wtrbjytDbk=
  file_glob: true
  file: "../${REPO_NAME}-${GIT_TAG}.zip"
  on:
    repo: medfreeman/wp-theme-starter
    branch: travisci
    tags: false
