sudo: required
dist: trusty
language: node_js

node_js:
  - '5'
  - '6'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # nodejs >v4 compiler requirements
      - g++-4.8
      - openjdk-7-jdk
      - php5-cli

# fail asap when there is a failure
matrix:
  fast_finish: true

# cache node modules
cache:
  directories:
    - node_modules

before_install:
  # faster npm install
  - npm set progress=false
  # remove useless/non listed deps
  - npm prune

before_script: npm test

script: npm run prod

env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=development